### ISSUE TITLE
Push data package to OpenSpending Datastore

### ISSUE THREAD

**Issue by pwalsh** [openspending/os-packager#49]
# Description

At the last step of the packager, we want to provide one-click publication of the whole data package to the OpenSpending Datastore. This publication method will be in *addition* to the current option to download the created package.

In general, publishing to the OpenSpending Datastore will require we have a [known user](https://github.com/openspending/fiscal-data-packager/issues/50). This task is just to get the upload flow working and stable before we properly integrate users.

The basic requirement is that a user passes in a CSV, models data, and then does "one-click" publishing to the new OpenSpending Datastore.

# Tasks

* [x] Add new action to the final step: "Publish this Data Package"
* [x] Integrate with the `os-conductor` service to get authorisation to make the file uploads to S3
  * [x] The base URL for the conductor service should be in an ENVAR. Example: `OS_CONDUCTOR=http://os-conductor.herokuapp.com`
  * [x] As we are mocking some aspects here until #50, use:
    * [x] A fake key which mocks your "user" @pwalsh to provide, and read it from an ENVVAR so it is not in codebase
    * [x] Always write into a directory called `__tests` which is where we do our testing work :). that means that `__tests` is your username
  * [x] Process each file for upload to get build the info the service needs and the form of the object it expects (below)
  * [x] Handle the response which has the data you passed the service, plus the new, temporary URLs from Amazon to upload, for each file
    * [x] Handle auth errors here - e.g.: user token is incorrect
* [x] Queue all files for upload to their destinations - probably good to use web workers
* [x] Add a progress element *for datastore upload* with:
  * [x] List of all files to upload
  * [x] Progress bar for each file
* [x] When upload complete, return the USER the new URL to the live `datapackage.json` file
* [x] When datastore upload is complete, we need to trigger another process on the backend  - writing data from datastore into a database for the API.  So, we need to call a webhook on the conductor to initiate the loading (POST to `{OS_CONDUCTOR}/hooks/load/api`) and report that progress to the user too, as a progress indicator that appears *after* the datastore stuff is finished
  * [x] "Loading data to the API"
  * [x] To get progress, poll against `{OS_CONDUCTOR}/hooks/load/api`
    * [x] Can expose poll rate as env var too, default to every 3 seconds
  * [x] POST/GET parameters for `{OS_CONDUCTOR}/hooks/load/api`: "datapackage": {URL_TO_PACKAGE}
    * [x] Response body when polling will be `{"progress": {numeric progress indicator}, "status": "progress/success/fail", "error": "In case of failures, will have an error message"}`
* [x] To solve: do we need to pull in files via URL before we upload, or can we just get the info we need from their remote location, and then upload them with our proxy?
* [x] Tests

### Data payload for access

endpoint: http://os-conductor.herokuapp.com/datastore/
```
# headers
API-Key // the API key

# body
{
  {
    "metadata": {
      "owner": // user who owns this package ,
      "name": // name of this data package,
    },
    "filedata": {
      "{FILEPATH}": {
        "md5": // md5 hash of the file,
        "name": // name of the file,
        "length": // length of the file,
        "upload_url": // upload url for this file,
        "upload_query": // upload query for this file,
      }
    }
  }
}

```

**Comment by pwalsh** [comment]
DONE :)
